### ISSUE TITLE
Still waiting for DB service...

### ISSUE THREAD

**Issue by Norbell** [million12/docker-mariadb#3]
Hello guys,

I'm trying to run your mariadb container in the DigitalOcean Docker 1.6 Droplet. 
I use the commands of your readme, but even after 5 minutes mariadb is still not started. 
In the logs I only see the message: "Still waiting for DB service...". 
For me this sounds like the "Container-OS" is not able to start the server.
Is this because of ubuntu being the host os? 

Thank you!

**Comment by pozgo** [comment]
Hi,
First question pops in to my mind is how much RAM memory that server have. As far as I remember the minimum for that image was 1GB for proper deployment. If possible please send us whole log messages.(maybe except the password :)) 

`docker logs -f container-name`

**Comment by Norbell** [comment]
@pozgo : Thank you for your response looks like the problem was because of a to small RAM. I used the smallest droplet with only 512 MB RAM. Now I choose a bigger one and everything starts instantly correctly. 

Thank you very much!

**Comment by ryzy** [comment]
Yeah, I've just added the note about 1GB memory requirement in README.md.
